imports:
    - { resource: topfive_constants.yml }

services:
    rmcgirr83.topfive.admin.controller:
        class: rmcgirr83\topfive\controller\admin_controller
        arguments:
            - '@cache'
            - '@config'
            - '@language'
            - '@request'
            - '@template'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%topfive_constants%'

    rmcgirr83.topfive.topfive:
        class: rmcgirr83\topfive\core\topfive
        arguments:
            - '@auth'
            - '@config'
            - '@cache'
            - '@content.visibility'
            - '@dbal.conn'
            - '@dispatcher'
            - '@language'
            - '@template'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@?senky.relativedates.listener'
            - '@?rmcgirr83.nationalflags.nationalflags'

    rmcgirr83.topfive.listener:
        class: rmcgirr83\topfive\event\listener
        arguments:
            - '@rmcgirr83.topfive.topfive'
            - '@config'
            - '@language'
            - '@template'
            - '@user'
            - '@controller.helper'
            - '%core.php_ext%'
            - '%topfive_constants%'
            - '@?phpbb.collapsiblecategories.operator'
        tags:
            - { name: event.listener }
